# coding: utf-8

"""
    Ecosyste.ms: Repos

    An open API service providing repository metadata for many open source software ecosystems.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.repos.models.dependency import Dependency

class TestDependency(unittest.TestCase):
    """Dependency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dependency:
        """Test Dependency
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dependency`
        """
        model = Dependency()
        if include_optional:
            return Dependency(
                id = 56,
                package_name = '',
                ecosystem = '',
                requirements = '',
                kind = '',
                direct = True,
                optional = True
            )
        else:
            return Dependency(
        )
        """

    def testDependency(self):
        """Test Dependency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
