# coding: utf-8

"""
    Ecosyste.ms: Repos

    An open API service providing repository metadata for many open source software ecosystems.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.repos.models.package_usage import PackageUsage

class TestPackageUsage(unittest.TestCase):
    """PackageUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageUsage:
        """Test PackageUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageUsage`
        """
        model = PackageUsage()
        if include_optional:
            return PackageUsage(
                ecosystem = '',
                name = '',
                dependents_count = 56,
                package_usage_url = '',
                dependencies_url = ''
            )
        else:
            return PackageUsage(
        )
        """

    def testPackageUsage(self):
        """Test PackageUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
