# coding: utf-8

"""
    Ecosyste.ms: Repos

    An open API service providing repository metadata for many open source software ecosystems.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ecosyste_ms_cli.clients.repos.models.repository import Repository
from ecosyste_ms_cli.clients.repos.models.topic import Topic
from typing import Optional, Set
from typing_extensions import Self

class TopicWithRepositories(BaseModel):
    """
    TopicWithRepositories
    """ # noqa: E501
    name: Optional[StrictStr] = None
    repositories_count: Optional[StrictInt] = None
    topic_url: Optional[StrictStr] = None
    related_topics: Optional[List[Topic]] = None
    repositories: Optional[List[Repository]] = None
    __properties: ClassVar[List[str]] = ["name", "repositories_count", "topic_url", "related_topics", "repositories"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TopicWithRepositories from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in related_topics (list)
        _items = []
        if self.related_topics:
            for _item_related_topics in self.related_topics:
                if _item_related_topics:
                    _items.append(_item_related_topics.to_dict())
            _dict['related_topics'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in repositories (list)
        _items = []
        if self.repositories:
            for _item_repositories in self.repositories:
                if _item_repositories:
                    _items.append(_item_repositories.to_dict())
            _dict['repositories'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TopicWithRepositories from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "repositories_count": obj.get("repositories_count"),
            "topic_url": obj.get("topic_url"),
            "related_topics": [Topic.from_dict(_item) for _item in obj["related_topics"]] if obj.get("related_topics") is not None else None,
            "repositories": [Repository.from_dict(_item) for _item in obj["repositories"]] if obj.get("repositories") is not None else None
        })
        return _obj


