# coding: utf-8

"""
    Ecosyste.ms: summary

    An open API service for producing an overview of a list of open source projects.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.summary.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_get_project(self) -> None:
        """Test case for get_project

        get a project by id
        """
        pass

    def test_get_projects(self) -> None:
        """Test case for get_projects

        get projects
        """
        pass

    def test_lookup_project(self) -> None:
        """Test case for lookup_project

        lookup project by url
        """
        pass


if __name__ == '__main__':
    unittest.main()
