# coding: utf-8

"""
    Ecosyste.ms: summary

    An open API service for producing an overview of a list of open source projects.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.summary.api.collections_api import CollectionsApi


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_get_collection(self) -> None:
        """Test case for get_collection

        get a collection by id
        """
        pass

    def test_get_collection_projects(self) -> None:
        """Test case for get_collection_projects

        get projects in a collection
        """
        pass

    def test_get_collections(self) -> None:
        """Test case for get_collections

        get collections
        """
        pass


if __name__ == '__main__':
    unittest.main()
