---
commitizen:
  major_version_zero: false
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 1.1.0
  version_files:
  - pyproject.toml:version
  - setup.py:version
  - ecosystems_cli/__init__.py:__version__
