# coding: utf-8

# flake8: noqa

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from ecosyste_ms_cli.clients.packages.api.dependencies_api import DependenciesApi
from ecosyste_ms_cli.clients.packages.api.keywords_api import KeywordsApi
from ecosyste_ms_cli.clients.packages.api.maintainers_api import MaintainersApi
from ecosyste_ms_cli.clients.packages.api.namespaces_api import NamespacesApi
from ecosyste_ms_cli.clients.packages.api.packages_api import PackagesApi
from ecosyste_ms_cli.clients.packages.api.registries_api import RegistriesApi

# import ApiClient
from ecosyste_ms_cli.clients.packages.api_response import ApiResponse
from ecosyste_ms_cli.clients.packages.api_client import ApiClient
from ecosyste_ms_cli.clients.packages.configuration import Configuration
from ecosyste_ms_cli.clients.packages.exceptions import OpenApiException
from ecosyste_ms_cli.clients.packages.exceptions import ApiTypeError
from ecosyste_ms_cli.clients.packages.exceptions import ApiValueError
from ecosyste_ms_cli.clients.packages.exceptions import ApiKeyError
from ecosyste_ms_cli.clients.packages.exceptions import ApiAttributeError
from ecosyste_ms_cli.clients.packages.exceptions import ApiException

# import models into sdk package
from ecosyste_ms_cli.clients.packages.models.advisory import Advisory
from ecosyste_ms_cli.clients.packages.models.dependency import Dependency
from ecosyste_ms_cli.clients.packages.models.keyword import Keyword
from ecosyste_ms_cli.clients.packages.models.keyword_with_packages import KeywordWithPackages
from ecosyste_ms_cli.clients.packages.models.maintainer import Maintainer
from ecosyste_ms_cli.clients.packages.models.namespace import Namespace
from ecosyste_ms_cli.clients.packages.models.package import Package
from ecosyste_ms_cli.clients.packages.models.package_with_registry import PackageWithRegistry
from ecosyste_ms_cli.clients.packages.models.registry import Registry
from ecosyste_ms_cli.clients.packages.models.version import Version
from ecosyste_ms_cli.clients.packages.models.version_with_dependencies import VersionWithDependencies
from ecosyste_ms_cli.clients.packages.models.version_with_package import VersionWithPackage
