# coding: utf-8

# flake8: noqa
"""
    Ecosyste.ms: Repos

    An open API service providing repository metadata for many open source software ecosystems.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ecosyste_ms_cli.clients.repos.models.dependency import Dependency
from ecosyste_ms_cli.clients.repos.models.dependency_with_repository import DependencyWithRepository
from ecosyste_ms_cli.clients.repos.models.ecosystem import Ecosystem
from ecosyste_ms_cli.clients.repos.models.host import Host
from ecosyste_ms_cli.clients.repos.models.manifest import Manifest
from ecosyste_ms_cli.clients.repos.models.owner import Owner
from ecosyste_ms_cli.clients.repos.models.package_usage import PackageUsage
from ecosyste_ms_cli.clients.repos.models.release import Release
from ecosyste_ms_cli.clients.repos.models.repository import Repository
from ecosyste_ms_cli.clients.repos.models.tag import Tag
from ecosyste_ms_cli.clients.repos.models.topic import Topic
from ecosyste_ms_cli.clients.repos.models.topic_with_repositories import TopicWithRepositories
