# coding: utf-8

"""
    Ecosyste.ms: Repos

    An open API service providing repository metadata for many open source software ecosystems.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DependencyWithRepository(BaseModel):
    """
    DependencyWithRepository
    """ # noqa: E501
    id: Optional[StrictInt] = None
    package_name: Optional[StrictStr] = None
    ecosystem: Optional[StrictStr] = None
    requirements: Optional[StrictStr] = None
    kind: Optional[StrictStr] = None
    direct: Optional[StrictBool] = None
    optional: Optional[StrictBool] = None
    repository: Optional[Dict[str, Any]] = None
    manifest: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "package_name", "ecosystem", "requirements", "kind", "direct", "optional", "repository", "manifest"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DependencyWithRepository from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of repository
        if self.repository:
            _dict['repository'] = self.repository.to_dict()
        # override the default output from pydantic by calling `to_dict()` of manifest
        if self.manifest:
            _dict['manifest'] = self.manifest.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DependencyWithRepository from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "package_name": obj.get("package_name"),
            "ecosystem": obj.get("ecosystem"),
            "requirements": obj.get("requirements"),
            "kind": obj.get("kind"),
            "direct": obj.get("direct"),
            "optional": obj.get("optional"),
            "repository": Repository.from_dict(obj["repository"]) if obj.get("repository") is not None else None,
            "manifest": Manifest.from_dict(obj["manifest"]) if obj.get("manifest") is not None else None
        })
        return _obj


