# coding: utf-8

# flake8: noqa
"""
    Ecosyste.ms: summary

    An open API service for producing an overview of a list of open source projects.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ecosyste_ms_cli.clients.summary.models.collection import Collection
from ecosyste_ms_cli.clients.summary.models.project import Project
