# coding: utf-8

# flake8: noqa

"""
    Ecosyste.ms: summary

    An open API service for producing an overview of a list of open source projects.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from ecosyste_ms_cli.clients.summary.api.collections_api import CollectionsApi
from ecosyste_ms_cli.clients.summary.api.projects_api import ProjectsApi

# import ApiClient
from ecosyste_ms_cli.clients.summary.api_response import ApiResponse
from ecosyste_ms_cli.clients.summary.api_client import ApiClient
from ecosyste_ms_cli.clients.summary.configuration import Configuration
from ecosyste_ms_cli.clients.summary.exceptions import OpenApiException
from ecosyste_ms_cli.clients.summary.exceptions import ApiTypeError
from ecosyste_ms_cli.clients.summary.exceptions import ApiValueError
from ecosyste_ms_cli.clients.summary.exceptions import ApiKeyError
from ecosyste_ms_cli.clients.summary.exceptions import ApiAttributeError
from ecosyste_ms_cli.clients.summary.exceptions import ApiException

# import models into sdk package
from ecosyste_ms_cli.clients.summary.models.collection import Collection
from ecosyste_ms_cli.clients.summary.models.project import Project
