# coding: utf-8

# flake8: noqa
"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ecosyste_ms_cli.clients.packages.models.advisory import Advisory
from ecosyste_ms_cli.clients.packages.models.dependency import Dependency
from ecosyste_ms_cli.clients.packages.models.keyword import Keyword
from ecosyste_ms_cli.clients.packages.models.keyword_with_packages import KeywordWithPackages
from ecosyste_ms_cli.clients.packages.models.maintainer import Maintainer
from ecosyste_ms_cli.clients.packages.models.namespace import Namespace
from ecosyste_ms_cli.clients.packages.models.package import Package
from ecosyste_ms_cli.clients.packages.models.package_with_registry import PackageWithRegistry
from ecosyste_ms_cli.clients.packages.models.registry import Registry
from ecosyste_ms_cli.clients.packages.models.version import Version
from ecosyste_ms_cli.clients.packages.models.version_with_dependencies import VersionWithDependencies
from ecosyste_ms_cli.clients.packages.models.version_with_package import VersionWithPackage
