# coding: utf-8

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.packages.models.keyword import Keyword

class TestKeyword(unittest.TestCase):
    """Keyword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Keyword:
        """Test Keyword
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Keyword`
        """
        model = Keyword()
        if include_optional:
            return Keyword(
                name = '',
                packages_count = 56,
                packages_url = ''
            )
        else:
            return Keyword(
                name = '',
                packages_count = 56,
                packages_url = '',
        )
        """

    def testKeyword(self):
        """Test Keyword"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
