# coding: utf-8

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.packages.api.dependencies_api import DependenciesApi


class TestDependenciesApi(unittest.TestCase):
    """DependenciesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DependenciesApi()

    def tearDown(self) -> None:
        pass

    def test_get_dependencies(self) -> None:
        """Test case for get_dependencies

        list dependencies
        """
        pass


if __name__ == '__main__':
    unittest.main()
