# coding: utf-8

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.packages.api.registries_api import RegistriesApi


class TestRegistriesApi(unittest.TestCase):
    """RegistriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegistriesApi()

    def tearDown(self) -> None:
        pass

    def test_get_registries(self) -> None:
        """Test case for get_registries

        list registies
        """
        pass

    def test_get_registry(self) -> None:
        """Test case for get_registry

        get a registry by name
        """
        pass


if __name__ == '__main__':
    unittest.main()
