# coding: utf-8

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.packages.api.keywords_api import KeywordsApi


class TestKeywordsApi(unittest.TestCase):
    """KeywordsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeywordsApi()

    def tearDown(self) -> None:
        pass

    def test_get_keyword(self) -> None:
        """Test case for get_keyword

        get a keyword by name
        """
        pass

    def test_get_keywords(self) -> None:
        """Test case for get_keywords

        list keywords
        """
        pass


if __name__ == '__main__':
    unittest.main()
