# coding: utf-8

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.packages.api.maintainers_api import MaintainersApi


class TestMaintainersApi(unittest.TestCase):
    """MaintainersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MaintainersApi()

    def tearDown(self) -> None:
        pass

    def test_get_registry_maintainer(self) -> None:
        """Test case for get_registry_maintainer

        get a maintainer by login or UUID
        """
        pass

    def test_get_registry_maintainer_packages(self) -> None:
        """Test case for get_registry_maintainer_packages

        get packages for a maintainer by login or UUID
        """
        pass

    def test_get_registry_maintainers(self) -> None:
        """Test case for get_registry_maintainers

        get a list of maintainers from a registry
        """
        pass


if __name__ == '__main__':
    unittest.main()
