# coding: utf-8

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from ecosyste_ms_cli.clients.packages.models.keyword import Keyword
from ecosyste_ms_cli.clients.packages.models.package import Package
from typing import Optional, Set
from typing_extensions import Self

class KeywordWithPackages(BaseModel):
    """
    KeywordWithPackages
    """ # noqa: E501
    name: StrictStr
    packages_count: StrictInt
    packages_url: StrictStr
    related_keywords: List[Keyword]
    packages: List[Package]
    __properties: ClassVar[List[str]] = ["name", "packages_count", "packages_url", "related_keywords", "packages"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KeywordWithPackages from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in related_keywords (list)
        _items = []
        if self.related_keywords:
            for _item_related_keywords in self.related_keywords:
                if _item_related_keywords:
                    _items.append(_item_related_keywords.to_dict())
            _dict['related_keywords'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in packages (list)
        _items = []
        if self.packages:
            for _item_packages in self.packages:
                if _item_packages:
                    _items.append(_item_packages.to_dict())
            _dict['packages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KeywordWithPackages from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "packages_count": obj.get("packages_count"),
            "packages_url": obj.get("packages_url"),
            "related_keywords": [Keyword.from_dict(_item) for _item in obj["related_keywords"]] if obj.get("related_keywords") is not None else None,
            "packages": [Package.from_dict(_item) for _item in obj["packages"]] if obj.get("packages") is not None else None
        })
        return _obj


