# coding: utf-8

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.packages.api.namespaces_api import NamespacesApi


class TestNamespacesApi(unittest.TestCase):
    """NamespacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NamespacesApi()

    def tearDown(self) -> None:
        pass

    def test_get_registry_namespace(self) -> None:
        """Test case for get_registry_namespace

        get a namespace by name
        """
        pass

    def test_get_registry_namespace_packages(self) -> None:
        """Test case for get_registry_namespace_packages

        get packages for a namespace by login or UUID
        """
        pass

    def test_get_registry_namespaces(self) -> None:
        """Test case for get_registry_namespaces

        get a list of namespaces from a registry
        """
        pass


if __name__ == '__main__':
    unittest.main()
