# coding: utf-8

"""
    Ecosyste.ms: Repos

    An open API service providing repository metadata for many open source software ecosystems.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.repos.models.owner import Owner

class TestOwner(unittest.TestCase):
    """Owner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Owner:
        """Test Owner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Owner`
        """
        model = Owner()
        if include_optional:
            return Owner(
                name = '',
                uuid = '',
                kind = '',
                email = '',
                login = '',
                company = '',
                location = '',
                description = '',
                twitter = '',
                website = '',
                metadata = None,
                icon_url = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                repositories_count = 56,
                last_synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                owner_url = '',
                repositories_url = '',
                html_url = '',
                funding_links = [
                    ''
                    ],
                total_stars = 56,
                followers = 56,
                following = 56
            )
        else:
            return Owner(
        )
        """

    def testOwner(self):
        """Test Owner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
