# coding: utf-8

"""
    Ecosyste.ms: Packages

    An open API service providing package, version and dependency metadata of many open source software ecosystems and registries.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.packages.api.packages_api import PackagesApi


class TestPackagesApi(unittest.TestCase):
    """PackagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PackagesApi()

    def tearDown(self) -> None:
        pass

    def test_get_registry_package(self) -> None:
        """Test case for get_registry_package

        get a package by name
        """
        pass

    def test_get_registry_package_dependent_package_kinds(self) -> None:
        """Test case for get_registry_package_dependent_package_kinds

        get a list of dependency kinds for a package
        """
        pass

    def test_get_registry_package_dependent_packages(self) -> None:
        """Test case for get_registry_package_dependent_packages

        get a list of packages that depend on a package
        """
        pass

    def test_get_registry_package_names(self) -> None:
        """Test case for get_registry_package_names

        get a list of package names from a registry
        """
        pass

    def test_get_registry_package_related_packages(self) -> None:
        """Test case for get_registry_package_related_packages

        get a list of packages that are related to a package
        """
        pass

    def test_get_registry_package_version(self) -> None:
        """Test case for get_registry_package_version

        get a version of a package
        """
        pass

    def test_get_registry_package_version_numbers(self) -> None:
        """Test case for get_registry_package_version_numbers

        get a list of version numbers for a package from a registry
        """
        pass

    def test_get_registry_package_versions(self) -> None:
        """Test case for get_registry_package_versions

        get a list of versions for a package
        """
        pass

    def test_get_registry_packages(self) -> None:
        """Test case for get_registry_packages

        get a list of packages from a registry
        """
        pass

    def test_get_registry_recent_versions(self) -> None:
        """Test case for get_registry_recent_versions

        get a list of recently published versions from a registry
        """
        pass

    def test_lookup_package(self) -> None:
        """Test case for lookup_package

        lookup a package by repository URL, purl or ecosystem+name
        """
        pass

    def test_lookup_registry_package(self) -> None:
        """Test case for lookup_registry_package

        lookup a package within a registry by repository URL, purl or ecosystem+name
        """
        pass


if __name__ == '__main__':
    unittest.main()
