# coding: utf-8

"""
    Ecosyste.ms: Repos

    An open API service providing repository metadata for many open source software ecosystems.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecosyste.ms
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecosyste_ms_cli.clients.repos.models.manifest import Manifest

class TestManifest(unittest.TestCase):
    """Manifest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Manifest:
        """Test Manifest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Manifest`
        """
        model = Manifest()
        if include_optional:
            return Manifest(
                ecosystem = '',
                filepath = '',
                sha = '',
                kind = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                repository_link = '',
                dependencies = [
                    ecosyste_ms_cli.clients.repos.models.dependency.Dependency(
                        id = 56, 
                        package_name = '', 
                        ecosystem = '', 
                        requirements = '', 
                        kind = '', 
                        direct = True, 
                        optional = True, )
                    ]
            )
        else:
            return Manifest(
        )
        """

    def testManifest(self):
        """Test Manifest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
